import React, { useState, useEffect } from 'react';
import { 
  XMarkIcon, 
  LanguageIcon, 
  CheckIcon, 
  DocumentTextIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon
} from '@heroicons/react/24/outline';
import { electronApi } from '../../utils/electronApi';

interface SubtitleTrack {
  code: string;
  name: string;
  auto: boolean;
  ext: string;
}

interface SubtitleSelectorProps {
  videoUrl: string;
  isVisible: boolean;
  onClose: () => void;
  onSelect: (selectedLanguages: string[], options: SubtitleOptions) => void;
}

interface SubtitleOptions {
  embed: boolean;
  autoGenerated: boolean;
  format: 'srt' | 'vtt' | 'ass';
  downloadSeparate: boolean;
}

export function SubtitleSelector({ videoUrl, isVisible, onClose, onSelect }: SubtitleSelectorProps) {
  const [availableSubtitles, setAvailableSubtitles] = useState<SubtitleTrack[]>([]);
  const [selectedLanguages, setSelectedLanguages] = useState<Set<string>>(new Set());
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [options, setOptions] = useState<SubtitleOptions>({
    embed: true,
    autoGenerated: true,
    format: 'srt',
    downloadSeparate: false
  });

  // Obtener subtítulos disponibles
  useEffect(() => {
    if (isVisible && videoUrl) {
      fetchAvailableSubtitles();
    }
  }, [isVisible, videoUrl]);

  const fetchAvailableSubtitles = async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      const process = electronApi.spawn('yt-dlp', [
        '--list-subs',
        '--skip-download',
        videoUrl
      ]);

      let output = '';

      process.stdout.on('data', (data: Buffer) => {
        output += data.toString();
      });

      process.stderr.on('data', (data: Buffer) => {
        // Error output handling if needed
        console.warn('yt-dlp stderr:', data.toString());
      });

      process.on('close', (code: number) => {
        if (code === 0) {
          const subtitles = parseSubtitleOutput(output);
          setAvailableSubtitles(subtitles);
        } else {
          setError('Failed to fetch subtitle information');
        }
        setIsLoading(false);
      });

      process.on('error', () => {
        setError('Failed to start subtitle fetch process');
        setIsLoading(false);
      });

    } catch (err) {
      setError('Error fetching subtitles');
      setIsLoading(false);
    }
  };

  const parseSubtitleOutput = (output: string): SubtitleTrack[] => {
    const lines = output.split('\n');
    const subtitles: SubtitleTrack[] = [];
    let inSubtitleSection = false;

    for (const line of lines) {
      if (line.includes('Available subtitles')) {
        inSubtitleSection = true;
        continue;
      }

      if (line.includes('Available automatic captions')) {
        inSubtitleSection = true;
        continue;
      }

      if (inSubtitleSection && line.trim()) {
        // Parsear líneas como: "en   English     vtt, ttml, srv3, srv2, srv1"
        const match = line.match(/^(\w+)\s+(.+?)\s+(.*)/);
        if (match) {
          const [, code, name, formats] = match;
          const isAuto = output.includes('automatic captions') && 
                        output.indexOf(line) > output.indexOf('automatic captions');
          
          subtitles.push({
            code: code.trim(),
            name: name.trim(),
            auto: isAuto,
            ext: formats.includes('srt') ? 'srt' : 'vtt'
          });
        }
      }
    }

    return subtitles;
  };

  const handleLanguageToggle = (langCode: string) => {
    const newSelected = new Set(selectedLanguages);
    if (newSelected.has(langCode)) {
      newSelected.delete(langCode);
    } else {
      newSelected.add(langCode);
    }
    setSelectedLanguages(newSelected);
  };

  const handleSelectAll = () => {
    if (selectedLanguages.size === availableSubtitles.length) {
      setSelectedLanguages(new Set());
    } else {
      setSelectedLanguages(new Set(availableSubtitles.map(sub => sub.code)));
    }
  };

  const handleApply = () => {
    onSelect(Array.from(selectedLanguages), options);
    onClose();
  };

  const popularLanguages = ['en', 'es', 'fr', 'de', 'pt', 'it', 'ru', 'ja', 'ko', 'zh'];
  
  const sortedSubtitles = availableSubtitles.sort((a, b) => {
    const aPopular = popularLanguages.indexOf(a.code);
    const bPopular = popularLanguages.indexOf(b.code);
    
    if (aPopular !== -1 && bPopular !== -1) return aPopular - bPopular;
    if (aPopular !== -1) return -1;
    if (bPopular !== -1) return 1;
    return a.name.localeCompare(b.name);
  });

  if (!isVisible) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-gray-800 rounded-lg max-w-2xl w-full max-h-[80vh] flex flex-col border border-gray-700">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-700">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-purple-600 rounded-lg flex items-center justify-center">
              <LanguageIcon className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Subtitle Options</h2>
              <p className="text-gray-400 text-sm">Select languages and download preferences</p>
            </div>
          </div>
          
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-white rounded-lg hover:bg-gray-700 transition-colors"
          >
            <XMarkIcon className="w-6 h-6" />
          </button>
        </div>

        {/* Options */}
        <div className="p-6 border-b border-gray-700">
          <h3 className="text-white font-medium mb-4">Subtitle Settings</h3>
          
          <div className="grid grid-cols-2 gap-4">
            <label className="flex items-center space-x-2">
              <input
                type="checkbox"
                checked={options.embed}
                onChange={(e) => setOptions({ ...options, embed: e.target.checked })}
                className="rounded bg-gray-700 border-gray-600 text-blue-600 focus:ring-blue-500"
              />
              <span className="text-gray-300 text-sm">Embed in video</span>
            </label>

            <label className="flex items-center space-x-2">
              <input
                type="checkbox"
                checked={options.downloadSeparate}
                onChange={(e) => setOptions({ ...options, downloadSeparate: e.target.checked })}
                className="rounded bg-gray-700 border-gray-600 text-blue-600 focus:ring-blue-500"
              />
              <span className="text-gray-300 text-sm">Download separate files</span>
            </label>

            <label className="flex items-center space-x-2">
              <input
                type="checkbox"
                checked={options.autoGenerated}
                onChange={(e) => setOptions({ ...options, autoGenerated: e.target.checked })}
                className="rounded bg-gray-700 border-gray-600 text-blue-600 focus:ring-blue-500"
              />
              <span className="text-gray-300 text-sm">Include auto-generated</span>
            </label>

            <div>
              <label className="block text-gray-300 text-sm mb-1">Format:</label>
              <select
                value={options.format}
                onChange={(e) => setOptions({ ...options, format: e.target.value as 'srt' | 'vtt' | 'ass' })}
                className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-1 text-white text-sm"
              >
                <option value="srt">SRT</option>
                <option value="vtt">VTT</option>
                <option value="ass">ASS</option>
              </select>
            </div>
          </div>
        </div>

        {/* Subtitles List */}
        <div className="flex-1 overflow-hidden flex flex-col">
          <div className="flex items-center justify-between p-4 border-b border-gray-700">
            <span className="text-white font-medium">Available Languages</span>
            <button
              onClick={handleSelectAll}
              className="text-blue-400 hover:text-blue-300 text-sm"
            >
              {selectedLanguages.size === availableSubtitles.length ? 'Deselect All' : 'Select All'}
            </button>
          </div>
          
          <div className="flex-1 overflow-y-auto p-4">
            {isLoading ? (
              <div className="text-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500 mx-auto mb-4"></div>
                <p className="text-gray-400">Loading subtitle information...</p>
              </div>
            ) : error ? (
              <div className="text-center py-8">
                <ExclamationTriangleIcon className="w-8 h-8 text-red-400 mx-auto mb-4" />
                <p className="text-red-400 mb-2">Error loading subtitles</p>
                <p className="text-gray-500 text-sm">{error}</p>
              </div>
            ) : sortedSubtitles.length === 0 ? (
              <div className="text-center py-8">
                <InformationCircleIcon className="w-8 h-8 text-gray-400 mx-auto mb-4" />
                <p className="text-gray-400">No subtitles available for this video</p>
              </div>
            ) : (
              <div className="space-y-2">
                {sortedSubtitles.map((subtitle) => (
                  <label
                    key={subtitle.code}
                    className="flex items-center space-x-3 p-3 rounded-lg hover:bg-gray-700 cursor-pointer transition-colors"
                  >
                    <input
                      type="checkbox"
                      checked={selectedLanguages.has(subtitle.code)}
                      onChange={() => handleLanguageToggle(subtitle.code)}
                      className="rounded bg-gray-700 border-gray-600 text-blue-600 focus:ring-blue-500"
                    />
                    <div className="flex-1">
                      <div className="flex items-center space-x-2">
                        <span className="text-white font-medium">{subtitle.name}</span>
                        <span className="text-gray-400 text-sm">({subtitle.code})</span>
                        {subtitle.auto && (
                          <span className="text-xs bg-yellow-600 text-yellow-100 px-2 py-0.5 rounded">
                            Auto
                          </span>
                        )}
                      </div>
                      <div className="text-gray-500 text-xs">
                        Format: {subtitle.ext.toUpperCase()}
                      </div>
                    </div>
                  </label>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-6 border-t border-gray-700">
          <div className="text-sm text-gray-400">
            {selectedLanguages.size > 0 
              ? `${selectedLanguages.size} language${selectedLanguages.size > 1 ? 's' : ''} selected`
              : 'No languages selected'
            }
          </div>
          
          <div className="flex items-center space-x-3">
            <button
              onClick={onClose}
              className="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-lg font-medium transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleApply}
              disabled={selectedLanguages.size === 0}
              className={`px-6 py-2 rounded-lg font-medium transition-colors flex items-center space-x-2 ${
                selectedLanguages.size > 0
                  ? 'bg-blue-600 hover:bg-blue-700 text-white'
                  : 'bg-gray-600 text-gray-400 cursor-not-allowed'
              }`}
            >
              <CheckIcon className="w-4 h-4" />
              <span>Apply Settings</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}